name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (including dev tools like ruff and pytest)
        run: uv sync --dev --locked

      - name: Run unit tests (Placeholder)
        run: echo "Unit tests are not implemented yet. Add tests and run 'uv run pytest' here."

  ruff:
    name: Run Ruff's linter
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Ruff
        run: uv sync --dev --locked

      - name: Run Ruff checks (Linting/Formatting)
        run: uv run ruff check .

  release_distributions:
    name: Build & upload to GitHub Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build sdist and wheel
        run: uv build

      - name: Check distribution integrity (using twine)
        run: |
          uv pip install twine
          uv run twine check dist/*

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: true
          name: Release ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }}

            This release contains the source distribution (.tar.gz) and a universal wheel (.whl) for manual installation.
